project_id = "xnhtuhvcrozgzcytnnco"

[functions.chat]
verify_jwt = false

[functions.deepsearch]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.gemini-tts]
verify_jwt = false
